### ISSUE TITLE
Problem with SSR

### ISSUE THREAD

**Issue by SilverDY** [viktorstrate/react-mathquill#8]
Hi. Did you try to use this project with Server Side Rendering? I have a problem during server-side rendering. `Cannot read property 'document' of undefined`. It happens when I import it (even if I don't use it further).

**Comment by viktorstrate** [comment]
Hi, it will probably be hard to make react-mathquill support SSR.
The problem is not with react-mathquill but rather mathquill itself.

The tricky part is exactly importing the library, see [mathquill-loader.js](https://github.com/viktorstrate/react-mathquill/blob/master/src/mathquill-loader.js)
Because mathquill accesses jQuery globally using `window.jQuery`, jQuery has to be globally exported.
This is done using the [exports-loader for Webpack](https://github.com/webpack-contrib/exports-loader).

The best way for this issue to be resolved, would be to remove jQuery from mathquill first.
This is also discussed in this thread mathquill/mathquill#670.
